This notebook run through a basic tutorial for loading scRNA-seq data using Scanpy. I utilize a single-cell mouse tissue dataset accessible at [GSE4230077](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM4230077).



# Set-Up and Installation

In [ ]:
#Upload your data to google drive
#Mount google drive in order to access the data
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [ ]:
#Install scanpy
!pip install --quiet scanpy

In [ ]:
#Import packages
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy as sp
import numpy as np
import scanpy as sc

# Loading the Data

In [ ]:
#Load the data to create an anndata object
adata_gsm4230077 = sc.read_10x_mtx("/content/drive/MyDrive/scrna_tutorials/gsm4230077", var_names="gene_ids",cache=True, gex_only=True, prefix="gsm4230077_")

In [ ]:
#Let's look at how many cell and gene counts are contained in the dataset
adata_gsm4230077

AnnData object with n_obs × n_vars = 5517 × 27998
    var: 'gene_symbols'

The AnnData object contains 5517 cells and 27998 genes.

In [ ]:
#Here,we can observe the cellular attributes of the data
adata_gsm4230077.obs

Empty DataFrame
Columns: []
Index: [AAACCTGAGTCGCCGT-1, AAACCTGAGTTAACGA-1, AAACCTGCAACGATGG-1, AAACCTGCAAGTCATC-1, AAACCTGCAATAGCGG-1, AAACCTGCACGTCAGC-1, AAACCTGCAGGGTTAG-1, AAACCTGGTCCCTACT-1, AAACCTGGTCCGAGTC-1, AAACCTGGTGTAATGA-1, AAACCTGGTTCAACCA-1, AAACCTGTCATGTAGC-1, AAACCTGTCGCATGGC-1, AAACGGGAGAGGTTGC-1, AAACGGGAGGCTAGGT-1, AAACGGGAGTATGACA-1, AAACGGGCAATAGCGG-1, AAACGGGCATGACGGA-1, AAACGGGCATGGAATA-1, AAACGGGGTAGCACGA-1, AAACGGGTCCCTGACT-1, AAAGATGAGAAGGCCT-1, AAAGATGAGACACGAC-1, AAAGATGAGGCCCTCA-1, AAAGATGCAAGGACAC-1, AAAGATGCAGTCAGAG-1, AAAGATGGTCTCATCC-1, AAAGATGGTGGTCCGT-1, AAAGATGTCATGCAAC-1, AAAGATGTCCATGCTC-1, AAAGATGTCCGTACAA-1, AAAGATGTCTAACCGA-1, AAAGATGTCTTAACCT-1, AAAGCAAAGAGTAATC-1, AAAGCAACAAGGACAC-1, AAAGCAACAGACGTAG-1, AAAGCAACATGCTGGC-1, AAAGCAAGTAAGCACG-1, AAAGCAAGTCGCGTGT-1, AAAGCAAGTGCAGTAG-1, AAAGCAAGTGGTCTCG-1, AAAGCAAGTGTAACGG-1, AAAGCAATCAGCGACC-1, AAAGCAATCGTACGGC-1, AAAGTAGCAAGAAGAG-1, AAAGTAGCACTCTGTC-1, AAAGTAGCAGGGTATG-1, AAAGTAGCATCCTAGA-1, AAAGTAGCATGGAATA-1, AAAGTAGCATTGGCGC-1, AAAGTAGGTAGCCTAT-1, AAAGTAGGTCGACTAT-1, AAAGTAGGTGTTGAGG-1, AAAGTAGTCGACCAGC-1, AAAGTAGTCGTATCAG-1, AAATGCCAGAGGGCTT-1, AAATGCCAGCTAGTGG-1, AAATGCCAGTGACATA-1, AAATGCCCAGCATACT-1, AAATGCCGTCACACGC-1, AAATGCCGTCATCCCT-1, AAATGCCGTGTGACGA-1, AAATGCCTCACCACCT-1, AAATGCCTCACCATAG-1, AACACGTAGGAGTAGA-1, AACACGTAGTTTGCGT-1, AACACGTCAACGATCT-1, AACACGTCAATAGCAA-1, AACACGTCAATGTTGC-1, AACACGTCACTGAAGG-1, AACACGTCAGAGCCAA-1, AACACGTGTACAGACG-1, AACACGTGTAGAAGGA-1, AACACGTTCACAGTAC-1, AACACGTTCAGAGACG-1, AACACGTTCCACGTGG-1, AACACGTTCGGAAATA-1, AACACGTTCTTTACAC-1, AACCATGAGCCGTCGT-1, AACCATGAGCGATTCT-1, AACCATGAGTAGCGGT-1, AACCATGCAAAGTGCG-1, AACCATGCAGTATCTG-1, AACCATGGTCATCGGC-1, AACCATGGTCGGGTCT-1, AACCATGGTCTTGTCC-1, AACCATGGTGGGTCAA-1, AACCATGGTTAAGATG-1, AACCATGGTTGCTCCT-1, AACCATGGTTTAGGAA-1, AACCATGTCCAGAAGG-1, AACCATGTCCCATTAT-1, AACCGCGAGATCTGAA-1, AACCGCGAGATGCCAG-1, AACCGCGCACTAAGTC-1, AACCGCGCATTGCGGC-1, AACCGCGGTACCGCTG-1, AACCGCGGTATGAAAC-1, AACCGCGGTCCGAACC-1, AACCGCGGTGCCTGGT-1, ...]

[5517 rows x 0 columns]

In [ ]:
#Here,we can observe the genetic attributes of the data
adata_gsm4230077.var

gene_symbols
ENSMUSG00000051951            Xkr4
ENSMUSG00000089699          Gm1992
ENSMUSG00000102343         Gm37381
ENSMUSG00000025900             Rp1
ENSMUSG00000109048             Rp1
...                            ...
ENSMUSG00000079808      AC168977.1
ENSMUSG00000095041            PISD
ENSMUSG00000063897           DHRSX
ENSMUSG00000096730        Vmn2r122
ENSMUSG00000095742  CAAA01147332.1

[27998 rows x 1 columns]